export const FrameWork =[
    
    {
        library:"Reactjs",
        img:"https://assets.stickpng.com/images/584830f5cef1014c0b5e4aa1.png",
        desc:""
    },
    {
        library:"Nextjs",
        img:"https://www.datocms-assets.com/75941/1657707878-nextjs_logo.png",
        desc:""
    },
    {
        library:"Vite",
        img:"https://logos-download.com/wp-content/uploads/2022/01/VITE_Logo.png",
        desc:""
    },
    {
        library:"ChakraUi",
        img:"https://archive.org/download/github.com-chakra-ui-chakra-ui_-_2020-02-13_17-20-29/cover.jpg",
        desc:""
    },
    {
        library:"Tailwind",
        img:"https://files.raycast.com/sjxs3pxsc6k63ju0fzv8l3cu4v90",
        desc:""
    },
    {
        library:"MaterialUi",
        img:"",
        desc:""
    },
    {
        library:"SCSS",
        img:"",
        desc:""
    },
    {
        library:"MaterialUi",
        img:"",
        desc:""
    },
    {
        library:"MaterialUi",
        img:"",
        desc:""
    },
    {
        library:"MaterialUi",
        img:"",
        desc:""
    },
]